<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    
    <parent>
        <artifactId>lutece-global-pom</artifactId>
        <groupId>fr.paris.lutece.tools</groupId>
        <version>6.0.0</version>
    </parent>
    
    <modelVersion>4.0.0</modelVersion>
    <groupId>fr.paris.lutece.plugins</groupId>
    <artifactId>module-captcha-jcaptcha</artifactId>
    <packaging>lutece-plugin</packaging>
    <version>2.2.2-SNAPSHOT</version>
    <name>Lutece captcha jcaptcha module</name>
    
    <repositories>
        <repository>
            <id>lutece</id>
            <name>luteceRepository</name>
            <url>https://dev.lutece.paris.fr/maven_repository</url>
            <layout>default</layout>
        </repository>
        <repository>
            <id>repojcaptcha</id>
            <name>repojcaptcha</name>
            <url>https://archiva-repository.apache.org/archiva/repository/public</url>
        </repository>

</repositories>
    
    <dependencies>
        <dependency>
            <groupId>fr.paris.lutece.plugins</groupId>
            <artifactId>plugin-captcha</artifactId>
            <version>[2.2.0,2.9.9)</version>
            <type>lutece-plugin</type>
        </dependency>
        <dependency>
            <groupId>com.octo.captcha</groupId>
            <artifactId>jcaptcha</artifactId>
            <version>[2.0-alpha-1]</version>
        </dependency>
        <dependency>
            <groupId>com.octo.captcha</groupId>
            <artifactId>jcaptcha-api</artifactId>
            <version>[2.0-alpha-1]</version>
        </dependency>
        <dependency>
            <groupId>com.jhlabs</groupId>
            <artifactId>imaging</artifactId>
            <version>01012005-imagecompletefix-45</version>
        </dependency>
        <dependency>
            <groupId>com.octo.captcha</groupId>
            <artifactId>jcaptcha-extension-buffered-engine</artifactId>
            <version>1.0</version>
            <exclusions>
                <!-- already in lutece-core -->
                <exclusion>
                    <groupId>quartz</groupId>
                    <artifactId>quartz</artifactId>
                </exclusion>
            </exclusions>            
        </dependency>
        <dependency>
            <groupId>tritonus</groupId>
            <artifactId>tritonus-share</artifactId>
            <version>0.3.6</version>
        </dependency>
        <dependency>
            <groupId>tritonus</groupId>
            <artifactId>tritonus-dsp</artifactId>
            <version>0.3.6</version>
        </dependency>
    </dependencies>
    
    <properties>
        <componentName>jcaptcha</componentName>
        <jiraProjectName>JCAPTCHA</jiraProjectName>
        <jiraComponentId>10156</jiraComponentId>
    </properties>
    
    <scm>
        <connection>scm:git:https://github.com/lutece-platform/lutece-tech-module-captcha-jcaptcha.git</connection>
        <developerConnection>scm:git:https://github.com/lutece-platform/lutece-tech-module-captcha-jcaptcha.git</developerConnection>
        <url>https://github.com/lutece-platform/lutece-tech-module-captcha-jcaptcha.git</url>
      <tag>HEAD</tag>
  </scm>

</project>